apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-tekton-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/robertorodriguez98/pruebatekton1.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - Replace=true
    - CreateNamespace=true


